### ISSUE TITLE
HSV-2 + RefSeq ID

### ISSUE THREAD

**Issue by afonsoguerra** [ojcharles/hsvdrg#1]
Good stuff. Can you add the HSV-2 muts and add the RefSeq ID of the reference the mutations refer to in the genotype column? It's particularly relevant if you are using older studies as they might be using older reference versions (even if they have the same main ID).

**Comment by ojcharles** [comment]
added hsv2 data. 
Although I have noticed errors in the review papers data.
inconsistent fold change -> res/polymorphism phenotype assignment. within a single and between drugs.
CDV in 2 places is recorded as both resistant and sensitive to a mutation

**Comment by ojcharles** [comment]
This is now obsolete.
there is an upcoming herpes generic database and tool
http://cmv-resistance.ucl.ac.uk/herpesdrg
